In [1]:
import pandas as pd
import numpy as np

In [7]:
from google.colab import files

uploaded = files.upload()

Saving uncleaned_sales_data.csv to uncleaned_sales_data.csv

In [8]:
df = pd.read_csv("uncleaned_sales_data.csv")

In [9]:
df.head()

,Sale_ID,Customer_Name,Country,Product,Sale_Date,Quantity,Price,Discount,Region,Revenue
0,S1000,NaN,USA,laptop,01-05-2026,2.0,1000.0,10.0,NaN,NaN
1,S1001,John,NaN,Laptop,NaN,NaN,2500.0,5.0,North,NaN
2,s1002,JOHN,India,laptop,May 1 2026,2.0,2500.0,10.0,NORTH,25000.0
3,S1003,NaN,INDIA,NaN,NaN,2.0,2500.0,0.0,NaN,5000.0
4,s1004,john,INDIA,Phone,01-05-2026,2.0,2500.0,NaN,NORTH,25000.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sale_ID        338 non-null    object
 1   Customer_Name  392 non-null    object
 2   Country        413 non-null    object
 3   Product        401 non-null    object
 4   Sale_Date      392 non-null    object
 5   Quantity       272 non-null    float64
 6   Price          313 non-null    float64
 7   Discount       305 non-null    float64
 8   Region         383 non-null    object
 9   Revenue        289 non-null    float64
dtypes: float64(4), object(6)
memory usage: 39.2+ KB

In [11]:
df.shape

(500, 10)

In [12]:
df.isnull().sum()

Sale_ID          162
Customer_Name    108
Country           87
Product           99
Sale_Date        108
Quantity         228
Price            187
Discount         195
Region           117
Revenue          211
dtype: int64

In [13]:
df.fillna("Unknown", inplace=True)

/tmp/ipykernel_2274/839676283.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("Unknown", inplace=True)

In [14]:
df.isnull().sum()

Sale_ID          0
Customer_Name    0
Country          0
Product          0
Sale_Date        0
Quantity         0
Price            0
Discount         0
Region           0
Revenue          0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.drop_duplicates(inplace=True)

In [17]:
df["Customer_Name"] = df["Customer_Name"].str.strip().str.lower()

df["Country"] = df["Country"].str.strip().str.title()

df["Product"] = df["Product"].str.strip().str.title()

df["Region"] = df["Region"].str.strip().str.title()

In [18]:
df["Sale_Date"] = pd.to_datetime(
    df["Sale_Date"],
    errors="coerce"
)

In [19]:
df.dtypes

Sale_ID                  object
Customer_Name            object
Country                  object
Product                  object
Sale_Date        datetime64[ns]
Quantity                 object
Price                    object
Discount                 object
Region                   object
Revenue                  object
dtype: object

In [21]:
df.to_csv(
    "cleaned_sales_data.csv",
    index=False
)

In [22]:
from google.colab import files

files.download("cleaned_sales_data.csv")